name: CI
on:
  push:
    branches: [ main ]
jobs:
  generate-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Github Tag Bump
      id: tab_bump
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.NUGET_API_KEY }}
        INITIAL_VERSION: 1.0.0
        DEFAULT_BUMP: patch
    outputs:
      new_version: ${{ steps.tab_bump.outputs.new_tag }}
  package-and-publish-contracts:
    runs-on: ubuntu-latest
    needs: generate-version
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
        source-url: https://nuget.pkg.github.com/${{github.repository_owner}}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}
    - name: Pack      
      run: |       

        mkdir -p packages  
        for proj in $(find . -name "*.csproj"); do      
            dotnet pack "$proj" --configuration Release --no-build \
            -p:PackageVersion=${{ needs.generate-version.outputs.new_version }} \
            -p:RepositoryUrl=https://github.com/${{ github.repository_owner }}/$(basename "$proj" .csproj) \
            -o packages
      
        for nupkg in packages/*.nupkg; do
        dotnet nuget push "$nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
        done
       